aus_states = ['ACT', 'NSW', 'NT', 'QLD', 'SA', 'TAS', 'VIC', 'WA']

us_regions = {
    1: ["Connecticut", "Maine", "Massachusetts", "New Hampshire", "Rhode Island", "Vermont"],
    2: ["New Jersey", "New York", "Pennsylvania"],
    3: ["Illinois", "Indiana", "Michigan", "Ohio", "Wisconsin"],
    4: ["Iowa", "Kansas", "Minnesota", "Missouri", "Nebraska", "North Dakota", "South Dakota"],
    5: ["Delaware", "Florida", "Georgia", "Maryland", "North Carolina", "South Carolina", "Virginia", "West Virginia"],
    6: ["Alabama", "Kentucky", "Mississippi", "Tennessee"],
    7: ["Arkansas", "Louisiana", "Oklahoma", "Texas"],
    8: ["Arizona", "Colorado", "Idaho", "Montana", "Nevada", "New Mexico", "Utah", "Wyoming"],
    9: ["Alaska", "California", "Hawaii", "Oregon", "Washington"]
}

state_subreddits = {
    "ACT": "canberra",
    "TAS": "tasmania",
    "NSW": "sydney",
    "NT": "darwin",
    "QLD": "brisbane",
    "VIC": "melbourne",
    "Washington": "seattle",
    "Alabama": "HuntsvilleAlabama",
    "Alaska": "Alaska",
    "Arizona": "phoenix",
    "Arkansas": "arkansas",
    "California": "LosAngeles",
    "Colorado": "Denver",
    "Connecticut": "Connecticut",
    "Delaware": "Delaware",
    "Florida": "Florida",
    "Georgia": "Georgia",
    "Hawaii": "Hawaii",
    "Idaho": "Boise",
    "Illinois": "Chicago",
    "Indiana": "Indianapolis",
    "Iowa": "Iowa",
    "Kansas": "Wichita",
    "Kentucky": "Louisville",
    "Louisiana": "NewOrleans",
    "Maine": "Maine",
    "Maryland": "Maryland",
    "Massachusetts": "Boston",
    "Michigan": "Michigan",
    "Minnesota": "Minnesota",
    "Mississippi": "Mississippi",
    "Missouri": "KansasCity",
    "Montana": "Montana",
    "Nebraska": "Omaha",
    "Nevada": "LasVegas",
    "New Hampshire": "NewHampshire",
    "New Jersey": "NewJersey",
    "New Mexico": "Alburquerque",
    "New York": "NewYorkCity",
    "North Carolina": "NorthCarolina",
    "North Dakota": "NorthDakota",
    "Ohio": "Ohio",
    "Oklahoma": "Oklahoma",
    "Oregon": "Portland",
    "Pennsylvania": "Philadelphia",
    "Rhode Island": "RhodeIsland",
    "South Carolina": "SouthCarolina",
    "South Dakota": "SouthDakota",
    "Tennessee": "Tennessee",
    "Texas": "texas",
    "Utah": "Utah",
    "Vermont": "Vermont",
    "Virginia": "Virginia",
    "West Virginia": "WestVirginia",
    "Wisconsin": "wisconsin",
    "Wyoming": "wyoming"
}
