state_subreddits = {
    "ACT": "canberra",
    "TAS": "tasmania",
    "NSW": "sydney",
    "NT": "darwin",
    "QLD": "brisbane",
    "VIC": "melbourne",
    "Washington": "seattle",
    "Alabama": "HuntsvilleAlabama",
    "Alaska": "Alaska",
    "Arizona": "phoenix",
    "Arkansas": "arkansas",
    "California": "LosAngeles",
    "Colorado": "Denver",
    "Connecticut": "Connecticut",
    "Delaware": "Delaware",
    "Florida": "Florida",
    "Georgia": "Georgia",
    "Hawaii": "Hawaii",
    "Idaho": "Boise",
    "Illinois": "Chicago",
    "Indiana": "Indianapolis",
    "Iowa": "Iowa",
    "Kansas": "Wichita",
    "Kentucky": "Louisville",
    "Louisiana": "NewOrleans",
    "Maine": "Maine",
    "Maryland": "Maryland",
    "Massachusetts": "Boston",
    "Michigan": "Michigan",
    "Minnesota": "Minnesota",
    "Mississippi": "Mississippi",
    "Missouri": "KansasCity",
    "Montana": "Montana",
    "Nebraska": "Omaha",
    "Nevada": "LasVegas",
    "New Hampshire": "NewHampshire",
    "New Jersey": "NewJersey",
    "New Mexico": "Alburquerque",
    "New York": "NewYorkCity",
    "North Carolina": "NorthCarolina",
    "North Dakota": "NorthDakota",
    "Ohio": "Ohio",
    "Oklahoma": "Oklahoma",
    "Oregon": "Portland",
    "Pennsylvania": "Philadelphia",
    "Rhode Island": "RhodeIsland",
    "South Carolina": "SouthCarolina",
    "South Dakota": "SouthDakota",
    "Tennessee": "Tennessee",
    "Texas": "texas",
    "Utah": "Utah",
    "Vermont": "Vermont",
    "Virginia": "Virginia",
    "West Virginia": "WestVirginia",
    "Wisconsin": "wisconsin",
    "Wyoming": "wyoming"
}